In [22]:
import numpy as np

# 1.创建数组


 定义一个三维序列
 
 ## 注意：这里的a既不是一个1*3的行向量，也不是一个3*1的列向量,因为他的shape只有一个维度
 

In [35]:
a = np.array([1,2,3],dtype=np.int64)
print(a)
print(a.dtype)
print(a.shape)

[1 2 3]
int64
(3,)


变a为1*3行向量，前面添加一个维度

In [36]:
row = a[np.newaxis,:]
print(row)
print(row.shape)

[[1 2 3]]
(1, 3)


变a为3*1列向量，后面添加一个维度

In [37]:
column = a[:, np.newaxis]
print(column)
print(column.shape)

[[1]
 [2]
 [3]]
(3, 1)


定义一个2行3列的矩阵

In [38]:
a = np.array([[1,2,3],
              [4,5,6]],dtype=np.int64)
print(a.shape)
print(a)

(2, 3)
[[1 2 3]
 [4 5 6]]


定义一个3行4列的零矩阵

In [39]:
a = np.zeros((3,4))
print(a)

[[0. 0. 0. 0.]
 [0. 0. 0. 0.]
 [0. 0. 0. 0.]]


定义一个有序向量

In [40]:
a = np.arange(1,11,2) # 从1到11步长为2，不包括11
print(a)

[1 3 5 7 9]


In [41]:
a= np.arange(12).reshape((3,4))
print(a)

[[ 0  1  2  3]
 [ 4  5  6  7]
 [ 8  9 10 11]]


In [42]:
a= np.linspace(1,10,12).reshape((3,4)) # 包括10
print(a)

[[ 1.          1.81818182  2.63636364  3.45454545]
 [ 4.27272727  5.09090909  5.90909091  6.72727273]
 [ 7.54545455  8.36363636  9.18181818 10.        ]]


定义一个3*4的随机矩阵,每个数字在（0，1）之间

In [43]:
a = np.random.random((3,4))
print(a)

[[0.07054612 0.11555931 0.01200948 0.34767824]
 [0.88914705 0.09732584 0.5714734  0.10648196]
 [0.16857669 0.31278401 0.97403713 0.51280819]]


# 2.基本操作

In [45]:
a = np.array([10,20,30,40])
b = np.arange(4) # 从0开始，到4，步长1
print(a)
print(b)

[10 20 30 40]
[0 1 2 3]


按元素计算向量平方


In [46]:
c = b**2
print(c)

[0 1 4 9]


按元素取10log10

In [47]:
c = 10*np.log10(a)
print(c)

[10.         13.01029996 14.77121255 16.02059991]


查看数组中哪些值小于三

In [48]:
print(b<3)

[ True  True  True False]


矩阵按元素相乘

In [49]:
a = np.array([[1,1],
              [0,1]])
b = np.arange(4).reshape((2,2))
print(a)
print(b)

[[1 1]
 [0 1]]
[[0 1]
 [2 3]]


In [51]:
c = a*b
print(c)

[[0 1]
 [0 3]]


矩阵相乘

In [50]:
c = np.dot(a,b)
c_2 = a.dot(b) # 与上面效果一样实现 a*b
print(c)

[[2 4]
 [2 3]]


# 3.数组合并

定义两个3*1的列向量

In [23]:
A = np.array([1,1,1])[:,np.newaxis]
B = np.array([2,2,3])[:,np.newaxis]
print(A)
print(B)
print(A.shape)

[[1]
 [1]
 [1]]
[[2]
 [2]
 [3]]
(3, 1)


垂直合并，vertical stack,拼接行

In [24]:
C = np.vstack((A,B)) 
print(C)

[[1]
 [1]
 [1]
 [2]
 [2]
 [3]]


水平合并 horizontal stack按列拼接

In [25]:
D = np.hstack((A,B))
print(D)

[[1 2]
 [1 2]
 [1 3]]


另一种合并方法 concatenate, axis=0相当于np.vstack，axis=1相当于np.hstack

记忆方法：1对列进行操作

In [26]:
E = np.concatenate((A,B,A,B),axis=1)
print(E)

[[1 2 1 2]
 [1 2 1 2]
 [1 3 1 3]]


# 4.数组分割

In [27]:
A = np.arange(12).reshape(3,4)
print(A)

[[ 0  1  2  3]
 [ 4  5  6  7]
 [ 8  9 10 11]]


一刀垂直切,同样1是对列进行操作

split(A,2) 其中2表示二等分，所有该方法只能等量分割

In [28]:
 print(np.split(A,2,axis=1))

[array([[0, 1],
       [4, 5],
       [8, 9]]), array([[ 2,  3],
       [ 6,  7],
       [10, 11]])]


不等量分割，比如上面的A矩阵有四列，可以分词2部分，但是分词三部分就报错了，下面函数可以实现不等分

In [29]:
print(np.array_split(A,3,axis=1))

[array([[0, 1],
       [4, 5],
       [8, 9]]), array([[ 2],
       [ 6],
       [10]]), array([[ 3],
       [ 7],
       [11]])]


一刀垂直切，另一种方法

In [30]:
print(np.hsplit(A,2))

[array([[0, 1],
       [4, 5],
       [8, 9]]), array([[ 2,  3],
       [ 6,  7],
       [10, 11]])]


# 5.数组复制

In [31]:
a = np.arange(4)
print(a)

[0 1 2 3]


numpy中数组赋值，b=a同样是意味着b指向了a的地址，所有a变化，b会同样变化,b变a也变

In [32]:
b = a
c = a
d = b
a[0] = 4
print('a的值=',a)
print('b的值=',b)
print('c的值=',c)
print('d的值=',d)

a的值= [4 1 2 3]
b的值= [4 1 2 3]
c的值= [4 1 2 3]
d的值= [4 1 2 3]


有时候，我把a复制给b,然后变a但是我不希望b跟着变，这时候就用copy

In [33]:
b = a.copy()
print('b的值=',b)
a[0] = 5
print('a的值=',a)

b的值= [4 1 2 3]
a的值= [5 1 2 3]
